pro/account/urls.py
from django.urls import path
from .views import (
    UserRegisterView, 
    UserLoginView, 
    UserLogoutView, 
    UserProfileView, 
    UserPasswordResetView, 
    UserPasswordResetDoneView, 
    UserPasswordResetConfirmView, 
    UserPasswordResetCompleteView,
    UserFollowView,
    UserUnfollowView,
    EditProfileView,
    )

app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', UserProfileView.as_view(), name='user_profile'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
	path('reset/done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', UserFollowView.as_view(), name="user_follow"),
    path('unfollow/<int:user_id>/', UserUnfollowView.as_view(), name="user_unfollow"),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),

]

pro/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

pro/home/urls.py
from django.urls import path
from .views import (
    HomeView, 
    PostDetailView,
    PostDeleteView, 
    PostUpdateView, 
    PostCreateView, 
    PostAddReplyView,
    PostLikeView,
    )

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', PostUpdateView.as_view(), name='post_update'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', PostAddReplyView.as_view(), name="add_reply"),
    path('like/<int:post_id>/', PostLikeView.as_view(), name="post_like"),
]

pro/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# مربوط به جلسه ی ۱۷ ایجاد مدل پست هست، اسلاگ رشته ای هستش که برای خوانایی یوآرال استفاده میشود
class Post(models.Model):
    # ریلیتد نیم میاد کمک میکنه که ما بفهمیم یو یوزر چند تا پست داره در اکانت قسمت یوزرپروفایل ویو خط دوم متد گت به جای کدش از همین ریلیتد نیم استفاده کردیم
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, unique=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} - {self.slug} - {self.created}'
    
    # این مربوط میشه به جلسه ی ۳۱ که میاد بر اساس پستهای ایجاد شده نزولی سفارش سازی میکنه
    class Meta:
         ordering = ['-created']
    
    # برای جلسه ۱۸ هستش که اینو نوشتیم برای مرتب شدن یوآرال پست دیتیلها
    def get_absolute_url(self):
         return reverse('home:post_detail', args=(self.id, self.slug))
    
	# جلسه ی ۴۰ اومدیم این رو نوشتیم که در ویو نشون بدیم چند بار لایک شده پست کاربر
    def like_count(self):
         return self.pvotes.count()
    
    # مربوط به جلسه ی ۴۰ که میاد میبینه اگه کسی پستی رو لایک کرده بود بیاد گزینه لایک رو دیسیبل کنه
    def user_can_like(self, user):
         user_like = user.uvotes.filter(post=self)
         if user_like.exists():
              return True
         return False
         
    
# مربوط به جلسه ی ۳۵هست که مدل کامنت گذاشتن رو نوشتیم
# نکته: اگر مدل کامنت بالای مدل پست بود باید پست رو داخل کوتیشن بذاریم ولی الان چون مدل کامنت پایین مدل پست هست خود پست رو مینویسیم و ایرادی نداره
class Comment(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
     body = models.TextField(max_length=400)
     reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
     is_reply = models.BooleanField(default=False)
     created = models.DateTimeField(auto_now_add=True)

     def __str__(self):
          return f'{self.user} - {self.body[:30]}'



# مربوط به جلسه ۴۰ لایک کردن
class Vote(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

     def __str__(self):
          return f'{self.user} votes {self.post.slug}'

pro/home/forms.py
from django import forms
from .models import Post, Comment

# مربوط به جلسه ی ۲۲ برای آپدیت فرم ساختیم که ازش در ویوش استفاده کنیم
# در جلسه ۲۴ میایم کریت هم قبل از آپدیت میذاریم در اسم کلاس چون جفت فرمها هم برای آپدیت و هم برای کریت یکیه
class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')


# این مربوط به جلسه ی ۳۷ دوره هستش که میاد یک فرمی رو برای پاسخ به کامنتها ایجاد میکنه که کاربری که براش کامنت اومده اگه خواست جواب بده به کامنتها ازش استفاده کنه
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
			'body': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Type your comment.'})
		}


# مربوط به جلسه ی ۳۹ هستش که میاد فرم مربوط به جواب کامنت رو میسازیم
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
			'body': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Type your response.'})
		}


# مربوط به جلسه ی ۴۱ دوره ساخت فرم سرچ کردن هستش
class PostSearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'size':'30'}))

pro/home/views.py
from django.shortcuts import (
    render, 
    redirect, 
    get_object_or_404,
    )
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from .models import (
    Post, 
    Comment, 
    Vote,
    )
from .forms import (
    PostCreateUpdateForm, 
    CommentCreateForm, 
    CommentReplyForm, 
    PostSearchForm,
    )
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    # مربوط به جلسه ی ۴۱ هست که کلاس سرچ فرم رو دادیم به این ویو
    form_class = PostSearchForm
    def get(self, request):
        posts = Post.objects.all()
        # مربوط به جلسه ی ۴۰ که برنامه ی سرچ کردن رو نوشتیم دو خط زیر اینه
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
        context = {
            'posts':posts,
            'form':self.form_class
            }
        return render(request, 'home/home.html', context)
    

class PostDetailView(View):
    # مربوط به جلسه ی ۳۷ برای کامنت گذاشتنه به رندر اضافه ش کردیم و در دیتیل شرطی نوشتیم که فقط کسایی که لاگین کردن بتونن کامنت بذارن
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    # مربوط به جلسه ی ۳۷ هست
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, post_id, post_slug):
        # post = get_object_or_404(Post, pk=post_id, slug=post_slug)
        # مربوط به جلسه ی ۳۶ هست که میاد از پستها کامنتهاشونو میخونه از مدل پست میریم ریلیتدنیم پست مدل کامنت رو همه شو میخونیم
        comments = self.post_instance.pcomments.filter(is_reply=False)
        # مربوط به جلسه ی ۴۰ هست که میاد از متدی که توی مدل نوشتیم استفاده میکنه که بگه اگه یوزر لایک کرده بود گزینه لایک رو دیسبیل بکنه توی تمپلیت تا دوخط بعد کن لایک که شرطه
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        context = {
            'post':self.post_instance, 
            'comments':comments, 
            'form':self.form_class, 
            'reply_form':self.form_class_reply,
            'can_like':can_like
            }
        return render(request, 'home/detail.html', context)
    
    # مربوط به جلسه ی ۳۷ هستش که میاد لاگین ریکوآیرد رو از طریق متد دیکوریتور میده به متدمون
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
           new_comment = form.save(commit=False)
           new_comment.user = request.user
           new_comment.post = self.post_instance
           new_comment.save()
           messages.success(request, 'Your comment submitted successfully.', 'success')
           return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)

# جلسه۲۱ ساخت دیلیت ویو برای حذف پست
class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post ,pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'You deleted post seccessfully!', 'success')
        else:
            messages.error(request, 'You cant delete this post', 'danger')
        return redirect('home:home')

# مربوط به جلسه ۲۲ ساخت ویوی آپدیت پستها
# در جلسه ۲۴ اومدیم کریت رو قبل از آپدیت به اسم کلاس وریبل کلاس پست آپدیت اضافه کردم چون تو فرمها اسمشو تغییر دادم
class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    # چون ما بررسی اینکه کاربری که درخواست آپدیت زده اگه آیدیش برابر نبود با آیدی پست بیاد پیغام ارور نشونش بده رو تکرار کرده بودیم در متد گت و پست اومدیم در متد دیسپچ این بررسی رو قرار دادیم که کدامون شلوغ نشه... برای جلسه ۲۲ هستش
    # متد ستاپ اطلاعاتی که قراره داخل متدها استفاده بشن رو داخل خودش ذخیره میکنه که یه بار بریم وصل شیم به دیتابیس
    # متد ستاپ قبل از دیسپچ اجرا خواهد شد
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)


    def dispatch(self, request,*args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, "You can't update this post!", 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    # جای آرگز و کیوارگز پست آیدی بود که از طریق یوآرال میومد ولی اگه ننویسیمش ارور میگیریم پس بنا به تمیزی کد باید به جاش از آرگز و گیوارگز استفاده کنیم
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form':form, 'post':post})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, "You updated this post.", 'success')
            return redirect('home:post_detail', post.id, post.slug)
        

# جلسه ی ۲۴ هست که مربوط به ساخت پست هست
class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'home/create.html', {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'You created a new post.', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)
        

# مربوط به جلسه ۳۹ ساخت ویوی پاسخ به کامنتها
class PostAddReplyView(LoginRequiredMixin, View):
	form_class = CommentReplyForm

	def post(self, request, post_id, comment_id):
		post = get_object_or_404(Post, id=post_id)
		comment = get_object_or_404(Comment, id=comment_id)
		form = self.form_class(request.POST)
		if form.is_valid():
			reply = form.save(commit=False)
			reply.user = request.user
			reply.post = post
			reply.reply = comment
			reply.is_reply = True
			reply.save()
			messages.success(request, 'Your reply submitted successfully', 'success')
		return redirect('home:post_detail', post.id, post.slug)


# ویوی مربوط به لایک کردن پستها
class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, 'You have already liked this post!', 'danger')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'You liked this post.', 'success')
        return redirect('home:post_detail', post.id, post.slug)

pro/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Social Network</title>
</head>
<body>
    {% include 'home/inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'home/inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>
</body>
</html>

pro/templates/home/create.html
{% extends 'home/base.html' %}

{% block content %}
    <h3>Create A New Post</h3><br>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-info" type="submit" value="Create">
    </form>
{% endblock %}

pro/templates/home/detail.html
{% extends 'home/base.html' %}

{% block content %}
    {% comment %} مربوط به جلسه ی ۲۱ هست که میگه اگر آیدی یوزری که لاگین کرده با آیدی یوزر پست یکی بود بیاد دیلیت و آپدیت رو نشون طرف بده ولی اگه برابر نبود نشون نده چون اون یوزر، پست رو ننوشته و آیدیش متفاوته {% endcomment %}
    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger mb-3" href="">DELETE</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-primary mb-3" href="">UPDATE</a>
    {% endif %}
    <h3>Detail</h3><br>
    <h4 class="mb-2">{{ post.title }}</h4>
    <div class="card p-3 lead text-dark bg-warning">
        <p><a style="color:black" href="{% url 'account:user_profile' post.user.id %}">{{ post.user.username }}</a> - {{ post.created|date:"Y_M_D" }}</p>
        <p class="card-body">{{ post.body|linebreaks }}</p>
    </div><br>

    {% comment %} مربوط به جلسه ی ۳۷ هستش که میاد شرط میذاره هرکس که لاگین کرده فقط بتونه کامنت بذاره {% endcomment %}
    {% if request.user.is_authenticated %}
        {% comment %} مربوط به جلسه ی ۴۰ که میاد لایک رو میگذاره دکمه شو {% endcomment %}
        {% comment %} نکته: با توجه به متدی که در مدل نوشتم و در ویو شرطش رو گذاشتم اگر کاربر لایک کنه پست رو دیسیبل میشه دکمه ی لایک که در کلاس زیر دیسیبل بین کن لایک قرار گرفته که وریبل ما در ویو بوده {% endcomment %}
        <a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} mb-2 btn btn-primary col-md-2">Like:{{ post.like_count}}</a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Send">
        </form>
    {% else %}
        <p class='alert alert-danger'>Only Logged In Users Can Comment!</p>
    {% endif %}<br>

    {% if request.user.is_authenticated %}
        {% comment %} مربوط به جلسه ی ۳۵ هستش که میایم کامنت گذاشتن رو به کاربر نشون میدیم {% endcomment %}
        <h4 class='badge col-md-2' style='background-color:blue; color:white; font-size:19px'>Comments: {{ comments.count }}</h4>
        {% for comment in comments %}
            <div class="card mt-3 bg-dark text-white">
                <p class="card-header">
                    {{ comment.user }} | {{ comment.created|timesince }} {% comment %} فیلتر تایم سینس نشون میده چند دقیقه یا ساعت یا روز قبل این کامنت نوشته شده {% endcomment %}
                </p>
                <p class="card-body">
                    {{ comment.body }}
                    {% comment %} این مربوط میشه به جلسه ی ۳۹ که میادپاسخ به کامنتها رو برای کاربرانی که برای پستشون کامنت اومده رو مشخص میکنه فرمش رو که از اون طریق جواب بدن به کامنتها {% endcomment %}
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                            {% csrf_token %}
                            <details class="p-3 text" style="color:white">
                                <summary>Reply</summary><br>
                                    {{ reply_form.as_p }}
                                <input class='btn btn-success' type="submit" value="Send">
                            </details>
                            {% comment %} یک ویوی جدید لازم دارم اضافه کردن ریپلای کامنت و یوآرال هم داره {% endcomment %}
                        </form>
                    {% endif %}
                    {% comment %} مربوط به جلسه ی ۳۸ که پاسخ به کامنت رو میومدیم نشون میدادیم از این طریق {% endcomment %}
                    {% with replies=comment.rcomments.all %}
                        {% for reply in replies %}
                            <p class='p-3 m-2 bg-primary text-white'>{{ reply.user }}:<br/>{{ reply.body }}</p>
                        {% endfor %}
                    {% endwith %}
                </p>
            </div>
        {% empty %}
            <p class="alert alert-danger">There is no comment here!</p>
        {% endfor %}
    {% else %}
            <p class="alert alert-warning">You must login for see comments!</p>
    {% endif %}
{% endblock %}

pro/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
    {% comment %} مربوط به جلسه ی ۴۱ هست که میایم فرم سرچ که ساخته بودیم رو اینجا نشونش میدیم {% endcomment %}
    <form action="" method='get'>
        {{ form }}
        <input type="submit" class='btn btn-success col-md-1' style='border-radius:7px' value='Search'>
    </form>
    <h3 class='mt-4'>Posts</h3><br>
    <div class="card">
        {% for post in posts%}
            <a href="{{ post.get_absolute_url }}" class="card-body" style="text-decoration:none;background-color:#61C6E8; color:black">{{ post.body|truncatewords:10 }}</a>
        {% empty %}
            <p class='alert alert-danger'>There is no any post here!</p>
        {% endfor %}
    </div>
{% endblock %}

pro/templates/home/update.html
{% extends 'home/base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Update">
    </form>
{% endblock %}